# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html

default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%=ENV.fetch("RAILS_MAX_THREADS") { 5 }%>
  host: <%=Rails.application.credentials[Rails.env.to_sym][:main_app_host]%>
  username: <%=Rails.application.credentials[Rails.env.to_sym][:main_app_user_name]%>
  password: <%=Rails.application.credentials[Rails.env.to_sym][:main_app_password]%>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: HRM_TOOL_development

test:
  <<: *default
  database: HRM_TOOL_test

production:
  <<: *default
  database: HRM_TOOL_production